package com.example.encryptor.crypto

import java.util.UUID

data class EncryptionHeader(
    val contentCipherIv: ByteArray,
    val masterKeyPasswordCipherIv: ByteArray,
    val passwordSalt: ByteArray,
    val passwordEncryptedMasterKey: ByteArray
) // The rest is autogenerated by the IDE to allow valid comparisons.
{
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as EncryptionHeader

        if (!contentCipherIv.contentEquals(other.contentCipherIv)) return false
        if (!masterKeyPasswordCipherIv.contentEquals(other.masterKeyPasswordCipherIv)) return false
        if (!passwordSalt.contentEquals(other.passwordSalt)) return false
        if (!passwordEncryptedMasterKey.contentEquals(other.passwordEncryptedMasterKey)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = contentCipherIv.contentHashCode()
        result = 31 * result + masterKeyPasswordCipherIv.contentHashCode()
        result = 31 * result + passwordSalt.contentHashCode()
        result = 31 * result + passwordEncryptedMasterKey.contentHashCode()
        return result
    }
}


data class BiometricMetadata (
    val keyAlias: UUID,
    val masterKeyBiometricCipherIv: ByteArray,
    val biometricallyEncryptedMasterKey: ByteArray
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as BiometricMetadata

        if (keyAlias != other.keyAlias) return false
        if (!masterKeyBiometricCipherIv.contentEquals(other.masterKeyBiometricCipherIv)) return false
        if (!biometricallyEncryptedMasterKey.contentEquals(other.biometricallyEncryptedMasterKey)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = keyAlias.hashCode()
        result = 31 * result + masterKeyBiometricCipherIv.contentHashCode()
        result = 31 * result + biometricallyEncryptedMasterKey.contentHashCode()
        return result
    }
}
